#Objective: Learn How to take input , convert to integer , do math, and learn function len()
print("hello"+ input("what is your name"))
print(input())
print(input())
print(input())
num1=int(input())
num2=int(input())
print(num1*num2)
length=len("Perviaz Ali Zhulfiqar Qalandar")
print(length)
print(len(input()))